@startuml
autonumber

participant "??" as ui

mainframe MD
box "Back-End" #LightBlue
participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "elevator:\nElevator" as elevator
participant "Mapper" as map
participant "dto:\nDTO" as dto
end box

box "Database"
database "Repository" as repo
end box

ui --> r: post (/buildings/{id}/elevators)
    activate r
        r -> ctrl : createElevator()
        activate ctrl
            ctrl -> svc : createElevator()
            activate svc
                svc -> repo : exists(buildingId)
                activate repo
                deactivate repo

                alt building not found
                    svc --> ctrl : error
                    ctrl --> r : error (412)
                    r --> ui : 412: Precondition Failed
                else building found
                    svc -> repo: allExist(floors)

                    activate repo
                    deactivate repo

                    alt floor(s) not found
                        svc --> ctrl : error
                        ctrl --> r : error (412)
                        r --> ui : 412: Precondition Failed
                    else floors found
                        svc --> elevator** : create()

                        activate elevator
                        deactivate elevator

                        alt elevator not created
                            svc --> ctrl : error
                            ctrl --> r : error (422)
                            r --> ui : 422: Unprocessable Content

                        else elevator created successfully
                            svc -> repo : save(elevator)

                            activate repo
                                svc -> map : toDTO(elevator)
                            deactivate repo

                            activate map
                                map --> dto** : create(elevator)
                                activate dto
                                    map --> svc : dto
                                deactivate dto
                            deactivate map

                            svc --> ctrl : dto
                            ctrl --> r : dto (201)
                            r --> ui : 201: Created
                        end
                    end
                end
            deactivate svc
        deactivate ctrl
    deactivate r

@enduml
