@startuml
autonumber


participant "MD" as mdr


    [-> mdr: POST (/buildings/{buildingId}/floors/{floorNumber}/rooms)
    activate mdr

    alt  floor not found
        [<-- mdr  : 404: Not Found
    else floor found
    alt room not created
        [<-- mdr  : 422: Unprocessable Content
    else room created successfully
        [<-- mdr  : 201: Created
        end
    end

    deactivate mdr


@enduml

