@startuml
autonumber

participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc
participant "Floor" as floor
participant "Building" as building
participant "Mapper" as map
participant "DTO" as dto


participant "Repository" as repo
database "Database" as db

[--> r: PATCH /building/{id}/floors/{floorNumber}/map
    activate r
        r ---> ctrl : uploadMap()
        activate ctrl
            ctrl -> svc : uploadMap(dto)
            activate svc
                svc -> repo : findByCodeNumber(buildingCode,floorNumber)
                activate repo
                    repo -> db  : find(buildingCode,floorNumber)
                    activate db
                    deactivate db
                    repo <-- db : floor
                    svc <-- repo : floor
                deactivate repo

                alt floor not found
                    svc --> ctrl : error
                    ctrl --> r : error (404)
                    [<--r : error(404)
                else floor found
                    note right of svc
                        check building dimensions
                    end note
                    alt mapDimensions exceeded buildingDimensions
                        svc --> ctrl : error
                        ctrl --> r : error (422)
                        [<--r : error(422)
                    else
                        svc --> floor : updateMap(dto)
                        activate floor
                        deactivate floor

                        svc --> repo : save(floor)
                        activate repo
                            repo -> db : save(floor)
                            activate db
                            deactivate db
                        deactivate repo
                        svc -> map : toDTO(building)
                        activate map
                            map --> dto** : create(floor)
                                map --> svc : dto
                        deactivate map
                        svc --> ctrl : dto
                        deactivate svc
                        ctrl --> r : dto (201)
                        deactivate ctrl
                        [<--r : 201: Created
                    end
                end
    deactivate r

@enduml
