@startuml
autonumber

actor "Campus Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
    usr -> sys : list building floors with passage
    activate sys
        sys --> usr : show buildings and requests one
    deactivate sys

    usr -> sys : choses building
    activate sys
        sys --> usr : show floors with passage
    deactivate sys
deactivate usr

@enduml
