@startuml
autonumber

actor "Fleet Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
    usr -> sys : wants to create robot type
    activate sys
        sys --> usr : requests data
    deactivate sys

    usr -> sys : provides data
    activate sys
    alt success
        sys --> usr : previews created robot type
    else robot type already exists
        sys --> usr : informs error
    else bad robot type parameters
        sys --> usr : informs error
    end
    deactivate sys
deactivate usr

@enduml
