@startuml
autonumber

participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "robot:\nRobot" as b
participant "Mapper" as map
participant "dto:\nDTO" as dto
participant "Repository" as repo

database "Database" as db

[--> r : POST /robots
activate r
    note right : verify if user is a \nfleet manager
    alt unkown user
        [<-- r : 401: Unauthorized
    else user not authorized
        [<-- r : 403: Forbidden
    else user authorized

    r -> ctrl : createRobot()
    activate ctrl
        ctrl -> svc : createRobot()
        activate svc
            svc -> repo : findRobotType(robotTypeCode)
            activate repo
                repo -> db : find()
                activate db
                    db --> repo : robotType
                deactivate db
                repo --> svc : robotType
            deactivate repo

            svc --> b ** : create()
            ' activate b
            ' deactivate b

            alt robot  not created
                svc --> ctrl : error
                ctrl --> r : error (422)
                [<-- r : 422: Unprocessable Content
            else robot  created successfully
            svc -> repo : save(robot)
            activate repo
                repo -> db : save()
                activate db
                deactivate db
            deactivate repo

            svc -> map : toDTO(robot)
            activate map
                map --> dto **: create(robot)

                ' activate dto
                ' deactivate dto

                map --> svc : dto
            deactivate map

            svc --> ctrl : dto
        deactivate svc

        ctrl --> r : dto (201)
    deactivate ctrl
    [<-- r: 201: Created
deactivate r

end
end

@enduml
