@startuml
autonumber

actor " " as actor
box "RobDroneGo"
participant "MD" as mdr

activate actor

    actor -> mdr: POST /building/{id}/floors

    activate mdr
    alt building not found
        mdr --> actor : 412: Precondition Failed
    else floor created successfully
        mdr --> actor : 201: Created
    end
    deactivate mdr

deactivate actor

@enduml
