@startuml
autonumber

participant "<<system>>\nMD" as mdr

[--> mdr: POST /building/{id}/floors

activate mdr
alt building not found
    [<--mdr : 404: not found
else building found
    alt floor already exists
        [<--mdr : 422: Unprocessable Content
    else floor doesn't exist
        [<--mdr : 201: Created
    end
end
deactivate mdr


@enduml
