@startuml
autonumber

actor "Campus Manager" as usr

participant "FE" as ui
participant "MD" as md

activate usr
    usr -> ui : wants to list elevators inside building
    activate ui
        ui -> md : GET /buildings
        note right of md : see US 170 documentation
        activate md

        alt building(s) not found
                md --> ui : 404: error
                ui --> usr : informs building(s) not found
        else building(s) found

                md --> ui : 200: buildings
                 deactivate md
                 ui --> usr : shows buildings and request one
    deactivate ui


    usr -> ui : chooses building
    activate ui
        ui -> md : GET /buildings/{id}/elevators
        note right of md : see US 290 documentation
        activate md

        alt elevator(s) not found
            md --> ui : 404: error
            ui --> usr : informs elevator(s) not found
        else elevator(s) found


            md --> ui : 200: elevators
        deactivate md

        ui --> usr : shows elevators

        end
    end
    deactivate ui
deactivate usr

@enduml
