@startuml
autonumber

actor "Campus Manager" as usr

participant "Front-end" as ui
participant "MD" as md

activate usr
    usr -> ui : wants to edit elevator
    activate ui
        ui -> md : GET /buildings
        activate md
            md --> ui : buildings
        deactivate md

        ui --> usr : show & request building
    deactivate ui

    usr -> ui : chooses building
    activate ui
        ui -> md : GET /buildings/{:bCode}/elevators
        activate md
            md --> ui : building elevators
        deactivate md

        ui --> usr : show building elevators
    deactivate ui

    alt
        usr -> ui : wants to edit the elevator's floors
        activate ui
            ui -> md : GET /buildings/{:bCode}/floors
            activate md
                md --> ui : building floors
            deactivate md

            ui --> usr : shows building floors
        deactivate ui
    end

    usr -> ui : chooses elevator & submits updated data
    activate ui
        ui -> md : PUT|PATCH /building/{:bCode}/elevators/{:eCode}
        note right of md : user can choose between a full (PUT) \nand a partial (PATCH) update
        activate md
            md --> ui : error/success
        deactivate md

        ui --> usr : inform error/success
    deactivate ui
deactivate usr

@enduml
