@startuml
autonumber

actor " " as actor
box "RobDroneGo"
participant "MD" as mdr


actor -> mdr: GET /passages
activate actor
    activate mdr
    alt building not found
        mdr --> actor : 412: Precondition Failed
    else building found
        alt passage not found
            actor <-- mdr : 412: Precondition Failed
        else passages found
            alt passages between buildings not found
                actor <-- mdr : 412: Precondition Failed
            else passages between buildings found

                actor <-- mdr : 200: "OK" Successful
            end
        end
    end

    deactivate mdr
deactivate actor


@enduml

