@startuml
autonumber

participant "MD" as mdr

[-> mdr : GET /passages

activate mdr
    alt floors/building not found
        [<-- mdr : 412: Precondition Failed
    else passage not found
        [<-- mdr : 412: Precondition Failed
    else passages sent
        [<-- mdr : 200: Ok
    end
deactivate mdr

@enduml
