@startuml
autonumber

participant "<<system>>\nSystem RobDroneGo" as sys

[-> sys : GET /passages

activate sys
    alt floors/building not found
        [<-- sys : 412: Precondition Failed
    else passage not found
        [<-- sys : 412: Precondition Failed
    else passages sent
        [<-- sys : 200: Ok
    end
deactivate sys

@enduml
