@startuml

skinparam component {
    FontSize 16
    BackgroundColor<<Apache>> LightCoral
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BorderColor black
    BackgroundColor DeepSkyBlue
    ArrowFontName Impact
    ArrowColor #FF6655
    ArrowFontColor #777777
}

package system {
    package "SPA" {
    }

    package "Planning" {
    }

    package "MDV" {
    }

    package "MDR" {
    }

    package "MDT" {
    }

    "SPA" .right.> "MDR"
    "SPA" .right.> "MDV"
    "MDV" .down.> "MDR"
    "MDR" .right.> "MDT"
    "MDT" .right.> "Planning"
    "MDR" ..> "Planning"
    "Planning" ..> "MDR"
}

'
' Regarding this implementation view, we were unsure between connecting the MDR directly
' to Planning or not. There are pros and cons in both approaches: When not connecting the
' MDR to Planning, we reduce the coupling but the system becomes harder to scale and
' some use cases that do not require the MDT are now dependent on the MDT.
' On the other hand, if we do connect the MDR directly to planning there will be more coupling
' and a circular dependency.

@enduml
