@startuml

skinparam component {
    FontSize 16
    BackgroundColor<<Apache>> LightCoral
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BorderColor black
    BackgroundColor DeepSkyBlue
    ArrowFontName Impact
    ArrowColor #FF6655
    ArrowFontColor #777777
}

package system {
    package "UI" {


    }

    package "Planning" {

    }

    package "MDV" {

    }

    package "MDR" {

    }

    "UI" .right.> "Planning"
    "UI" .right.> "MDV"
    "UI" .right.> "MDR"

    "Planning" .down.> "MDV"
    "MDV" .down.> "MDR"
}

@enduml
