@startuml

skinparam component {
    FontSize 16
    BackgroundColor<<Apache>> LightCoral
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BorderColor black
    BackgroundColor DeepSkyBlue
    ArrowFontName Impact
    ArrowColor #FF6655
    ArrowFontColor #777777
}

package "<<system>>\nRobDroneGo" {
    [Campus Management]
    [Fleet Management]
    [Task Management]
    [Planning]
}

' interior
' TODO

' exterior
[Campus Management] -up- "Campus Management API"
[Campus Management] -down- "Campus Management UI"
[Fleet Management] -up- "Fleet Management API"
[Fleet Management] -down- "Fleet Management UI"
[Task Management] -up- "Task Management API"
[Task Management] -down- "Task Management UI"

@enduml
