version: '3'

services:

  robdrone-ui:
    build:
      context: ./spa
      dockerfile: Dockerfile
    # environment:
      # MDV url
      # MDR url
      # api key
    ports:
      - 4200:2226
    depends_on:
        robdrone-mdv


  robdrone-mdv:
    build:
      context: ./mdv
      dockerfile: Dockerfile
    environment:
      # VITE_MDR_URL:   http://localhost:4000/api
      VITE_APP_TITLE: RobDroneGo-visualization
    ports:
      # TODO: check 8080
      - 8080:2228

# vim: ts=2 sts=2 sw=2
