version: '3.8'

services:

  robdrone-ui:
    build:
      context: ./spa
      dockerfile: Dockerfile
    # environment:
      # MDV url
      # MDR url
      # api key
    ports:
      - 4200:4200
        #depends_on:
        #- robdrone-mdv

# vim: ts=2 sts=2 sw=2
