@startuml
autonumber

actor "Campus Manager" as usr

participant "HTML + CSS + JS" as view
participant "Controller" as ctrl
participant "Service" as svc
participant "dto:\nMinMaxDTO" as m_dto
participant "dto:\nBuildingByFloorsDTO" as dto

participant "HTTP Params" as params
participant "HTTP Driver" as http

activate usr
    usr -> view : wants to list buildings between a minimum\nand maximum number of floors
    activate view
        view --> usr : requests minimum and maximum number of floors
    deactivate view

    usr -> view : provides minimum and maximum number of floors
    activate view
        view -> ctrl : onSubmit()
        activate ctrl
            ctrl --> m_dto** : create()
            activate m_dto
                m_dto --> ctrl : dto
            deactivate m_dto

            ctrl -> svc : getBuildingsByFloors(dto)
            activate svc
                svc --> params** : create()
                activate params
                    svc -> params : set(minFloors)
                    svc -> params : set(maxFloors)
                deactivate params

                svc -> http : get({baseURL}/buildings/)
                activate http
                    note right of http: see us180 documentation
                    http ->] : GET /buildings/?minFloors={min}&maxFloors={max}
                        alt success
                            http <--] : 200: buildings
                            http --> svc : observable

                            loop for each building
                                svc --> dto** : create()
                                activate dto
                                    dto --> svc : dto
                                deactivate dto
                            end

                            svc --> ctrl : dto[]
                            ctrl --> ctrl : buildings = dto[]
                            ctrl --> view : buildings
                            view --> usr : lists buildings
                        else building(s) not found
                            http <--] : 404: error
                            http --> svc : observable

                            svc --> ctrl : error
                            ctrl --> ctrl : buildings = []
                            note left: creates alert with the error message
                            ctrl --> view : buildings
                            view --> usr : alerts buildings not found
                deactivate http
            deactivate svc
        deactivate ctrl
    deactivate view
deactivate usr
end


@enduml
