@startuml
autonumber

actor "Campus Manager" as usr

participant "Campus UI" as ui
participant "Campus MD" as md

activate usr
    usr -> ui : wants to list passages between two buildings
    activate ui

        ui -> md : GET /buildings
        alt building(s) not found
            activate md
            note right of md : see US 170 documentation
                md --> ui : 404: error

            ui --> usr : informs error

        else building(s) found
            md --> ui : 200: buildings

            deactivate md
            ui --> usr : shows buildings and requests two
    deactivate ui

    usr -> ui : chooses two buildings
    activate ui
        ui -> md : GET /passages
        activate md


        alt same building
            md --> ui : 412: error
            ui --> usr: informs error
        else different building

        alt passages(s) not found
                note right of md : see US 260 documentation
                md --> ui: 404: error

            ui --> usr : informs error
        else passage(s) found
            md --> ui : 200: passages

            deactivate md
            ui --> usr : shows passages between\n two buildings
            end
        end
    end
    deactivate ui
deactivate usr

@enduml
