@startuml
autonumber

actor "Campus Manager" as usr

participant "FE" as ui
participant "MD" as md

activate usr
    usr -> ui : wants to list passages between two buildings
    activate ui

        ui -> md : GET /buildings
        note right of md : see US 170 documentation
        alt building(s) not found
            activate md

                md --> ui : 404: error

            ui --> usr : informs building(s) not found

        else building(s) found
            md --> ui : 200: buildings

            deactivate md
            ui --> usr : shows buildings and requests two
    deactivate ui

    usr -> ui : chooses two buildings
    activate ui
        ui -> md : GET /passages/?building1={buildingCode}&building2={buildingCode}
        note right of md : see US 260 documentation
        activate md


        alt same building
            md --> ui : 412: error
            ui --> usr: informs same building provided
        else different building

        alt passages(s) not found

                md --> ui: 404: error

            ui --> usr : informs passages(s) not found
        else passage(s) found
            md --> ui : 200: passages

            deactivate md
            ui --> usr : shows passages between\n two buildings
            end
        end
    end
    deactivate ui
deactivate usr

@enduml
