@startuml
autonumber

actor "Campus Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
usr -> sys : list floors from a building
    activate sys
        sys --> usr : requests data
    deactivate sys

    usr -> sys : provides data
    activate sys
    alt success
        sys --> usr : lists floors
    else error
        sys --> usr : informs error
    end
    deactivate sys
deactivate usr

@enduml
