@startuml
autonumber

actor "Fleet Manager" as usr

participant "FE" as ui


participant "MD" as md

activate usr
    usr -> ui : wants to list all fleet robots
    activate ui

    ui -> md: GET /robots
    activate md
    note right of md : see US 380 documentation

    alt robot(s) not found
        md --> ui : 404: error
        ui --> usr: informs robot(s) not found
    else robot(s) found
        md --> ui: 200: robots
    deactivate md
        ui --> usr : shows robots

        end
    deactivate ui
deactivate usr

@enduml
