@startuml
autonumber


participant "<<system>>\nSystem RobDroneGo" as sys


    [-> sys: PATCH/PUT  ( /buildings/{idb}/elevators/{ide} )
    activate sys

    alt building not found
        [<-- sys : 404: Not Found
    else building found

        alt elevator not found
        [<-- sys : 404: Not Found
        else elevator exists

            alt  elevator bad params
                [<-- sys : 422: Unprocessable Content
            else elevator edited successfully
                [<-- sys : 200: "OK" Successful
            end
        end
    end

    deactivate sys


@enduml
