@startuml
autonumber

participant "Route" as rt
participant "Controller" as ctrl
participant "Service" as svc
participant "Repository" as repo

participant "Mapper" as map
participant "dto:\nDTO" as dto

participant "DBDriver" as db

[-> rt : GET /buildings/:id/floors/passages

activate rt
    rt -> ctrl : floorsWithPassage()
    activate ctrl
        ctrl -> svc : floorsWithPassage(dto)
        activate svc
            svc -> repo : findByCode(buildingCode)
            activate repo
                repo -> db : find()
                activate db
                    db --> repo : building
                deactivate db

                repo --> svc : building
            deactivate repo

            alt building not found
                svc --> ctrl : error
                ctrl --> rt : error(404)
                [<- rt : response code 404
            else building found
                svc -> repo : floorsWithPassage(building)
                activate repo
                    repo -> db : find()
                    activate db
                        db --> repo : floors
                    deactivate db

                    repo --> svc : floors
                deactivate repo

                svc -> map : toDTO()
                activate map
                    map --> dto **:create()
                deactivate map
                svc --> ctrl : floors
            end
        deactivate svc

        alt empty list
            ctrl --> rt : error(404)
            [<- rt : response code 404
        else result  exists
            ctrl --> rt : floors (200)
            deactivate ctrl
            [<- rt : floors(200)
        end
deactivate rt

@enduml
