@startuml
autonumber

actor "Campus Manager" as usr

participant "Front-end" as ui
participant "MD" as md

activate usr
    usr -> ui : inhibit robot
    activate ui
        ui -> md : GET /robots
        activate md
            md --> ui : robots
        deactivate md

        ui --> usr : show available robots
    deactivate ui

    usr -> ui : chooses robot
    activate ui
        ui -> md : PATCH /robots/{:code}
        activate md
            md --> ui : error/success
        deactivate md

        ui --> usr : inform error/success
    deactivate ui
deactivate usr

@enduml
