@startuml
autonumber

actor "Fleet Manager" as usr

participant "Fleet Management" as mng

activate usr
    usr -> mng : create robottype
    activate mng
        mng --> usr : request data
    deactivate mng

    usr -> mng : provides data
    activate mng
        mng --> usr : inform error/success
    deactivate mng
deactivate usr

@enduml
