@startuml
autonumber

participant "MDR" as mdr

participant "MDT" as mdt

[-> mdr: GET /task/tasks

activate mdr

    mdr -> mdt : GET /jobs/non-approved
    activate mdt


    alt task(s) not found
        mdt --> mdr: 404: error
        [<-- mdr : 404: Not Found

    else task(s) found
        mdt --> mdr: tasks
        [<-- mdr : 200: "OK" Successful
        alt selects task
            [-> mdr: PATCH /task/{id}
            mdr -> mdt: PATCH /jobs/{id}
        else
            alt task not found
            mdt --> mdr: 404: error
            [<-- mdr : 404: Not Found
        else task approved successfully
            mdt --> mdr : 200: task
            [<-- mdr : 200: "OK" Successful
        deactivate mdt
            end
        end
    end
deactivate mdr

@enduml
