@startuml
autonumber

actor "Task Manager" as usr

participant "SPA" as ui
participant "MDR" as mdr
participant "MDT" as mdt

activate usr
    usr -> ui : wants to approve or reject a task
    activate ui
        ui -> mdr : GET /tasks?status=pending
        activate mdr
            mdr -> mdt : GET /jobs?status=pending

            activate mdt

alt task(s) not found
                mdt --> mdr : 200: empty list
                mdr --> ui : 200: empty list
                ui --> usr : inform no pending tasks available

else task(s) found
                mdt --> mdr : 200: tasks
            deactivate mdt

            mdr --> ui : 200: tasks
        deactivate mdr

        ui --> usr : shows tasks & requests one
    deactivate ui

    usr -> ui : approves/rejects chosen task
    activate ui
        ui -> mdr : PATCH /tasks/{id}
        activate mdr
            mdr -> mdt : PATCH /jobs/{id}
            activate mdt
                mdt --> mdr : 200: updated task
            deactivate mdt

            mdr --> ui : task
        deactivate mdr

            ui --> usr : shows updated task
    deactivate ui
deactivate usr
end

@enduml
