@startuml
autonumber

actor "??" as actor
participant "<<system>>\nSystem RobDroneGo" as sys

activate actor
actor -> sys : Starts building creation

activate sys
sys --> actor : Requests data(code, name, description)
deactivate sys

actor -> sys: Inserts requested data(code, name, description)
activate sys
sys --> actor : Message: building created / error in data inserted
deactivate sys


@enduml
