version: '3.8'

services:
  robdrone-db:
    image: mongo
    restart: always
      # environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      # MONGO_INITDB_DATABASE: 'prod'
      # ports:
      #   - 27017:27017
    networks:
      app_network:
        ipv4_address: 192.168.1.3




  robdrone-be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'robdrone-be'
    environment:
      NODE_ENV: 'production'
      PORT: 4000
      MONGODB_URI: 'mongodb+srv://root:iJwu80jbwERuTa4t@maincluster.ocd2dr6.mongodb.net/?retryWrites=true&w=majority'
      # TODO: planning url
    ports: 
      - 4000:2226
    depends_on:
      - robdrone-db
    networks:
      app_network:
       ipv4_address: 192.168.1.2
    healthcheck:
      test: ["CMD","curl","-f","http://localhost"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 1s


networks:
  app_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24


          # vim: ts=2 sts=2 sw=2
