@startuml
autonumber

actor "Task Manager" as usr

participant "<<system>>\n RobDroneGo" as sys

activate usr
    usr -> sys : wants to approve or refuse a task
    activate sys
        alt task(s) not found
            sys --> usr: informs error
        else task(s) found
        sys --> usr : request task
    deactivate sys


    usr -> sys : provides task
    activate sys
        alt task not found
            sys --> usr : informs error
        else task approved successfully
            sys --> usr : shows updated task
        end

        end
    deactivate sys
deactivate usr

@enduml
