@startuml
autonumber





participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc
participant "Mapper" as map
participant "dto:\nDTO" as dto
participant "Repository" as repo
database "Database" as db


[-> r: PATCH (/buildings/{idb}/elevators/{ide})
    activate r
            r -> ctrl : patchElevator(req,res,...)
                activate ctrl
                    ctrl -> svc : editElevator(idElevator,dto)
                    activate svc
                        svc -> repo : findByCode(buildingCode)
                        activate repo
                            repo -> db : findOne(bcode)
                            activate db
                            deactivate db
                        deactivate repo

                        alt building not found
                            svc --> ctrl : error
                            ctrl --> r : response 404
                            [<-- r : 404: Not Found



                        else building found

                            svc -> repo : exitsInBuilding(building,elevatorIdentifier)
                            activate repo
                                repo -> db : findOne(query)
                                activate db
                                deactivate db
                            deactivate repo

                            alt elevator not found
                                svc --> ctrl : error
                                ctrl --> r : response 404
                                [<-- r : 404: Not Found
                            else elevator exists

                                svc -> repo: findByIdentifier(building,elevatorIdentifier)
                                activate repo
                                    repo -> db : findOne(query)
                                    activate db
                                    deactivate db
                                deactivate repo

                                note right of svc
                                    edit building specifications
                                    based on new ones
                                end note


                            alt elevator bad parameters
                                svc --> ctrl : error
                                ctrl --> r : response 422
                                [<-- r : 422: Unprocessable Content
                            else elevator edited successfully
                               svc -> repo : save(elevator)
                               activate repo
                                    repo -> db: save()
                                    activate db
                                    deactivate db
                               deactivate repo




                            svc -> map : toDTO(elevator)
                            activate map
                                map --> dto **: create(elevator)
                                activate dto

                                map --> svc : dto
                                deactivate dto
                            deactivate map

                            svc --> ctrl : dto
                        deactivate svc

                        ctrl --> r : dto(200)
                    deactivate ctrl




            [<-- r: 200: "OK" Sucessful
                end
            end
         end
    deactivate r

@enduml
