@startuml
autonumber

actor "Campus Manager" as usr

participant "FE" as ui

participant "MD" as md

activate usr
    usr -> ui : wants to list buildings between a minimum\nand maximum number of floors
    activate ui
        ui --> usr : requests minimum and maximum number of floors
    deactivate ui

    usr -> ui : provides minimum and maximum number of floors
    activate ui
        ui -> md : GET /buildings/?minFloors={min}&maxFloors={max}
        activate md
            note right : see us180 documentation
            alt success
                md --> ui : 200: buildings
                ui --> usr : lists buildings
            else building(s) not found
                md --> ui : 404: error
                ui --> usr : alerts buildings not found
            end
        deactivate md
    deactivate ui
deactivate usr


@enduml
