@startuml
autonumber

participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "floor:\nFloor" as floor
participant "Mapper" as map
participant "dto:\nDTO" as dto

participant "Repository" as repo
database "Database" as db

[-> r: GET /buildings/{id}/floors
activate r
    r -> ctrl : getFloors()
    activate ctrl
        ctrl -> svc : getFloors()
        activate svc
            svc -> repo : findByCode()
            note right : tries to find building
            activate repo
                repo -> db : find()
                activate db
                    db --> repo : building
                deactivate db
                repo --> svc : building
            deactivate repo

            alt building not found
                svc --> ctrl : error
                ctrl --> r : error(404)
                [<-- r : 404: Not Found
            else building found
                svc -> repo : findByBuildingCode()
                note right : tries to find floors
                activate repo
                    repo -> db : find()
                    activate db
                        db --> repo : floors
                    deactivate db
                    repo --> svc : floors
                deactivate repo

                alt floors not found
                    svc --> ctrl : error
                    ctrl --> r : error (404)
                    [<-- r : 404: Not Found
                else floors found

                loop for each floor
                    svc -> map : toDTO(floor)

                    activate map
                        map --> dto** : create()
                        activate dto
                            map --> svc : dto
                        deactivate dto
                    deactivate map
                end loop

                    svc --> ctrl : dtoList
                    ctrl --> r : response
                    [<-- r : 200: OK
                end
            end
        deactivate svc
    deactivate ctrl
deactivate r

@enduml
