@startuml
autonumber

actor " " as actor
participant "<<system>>\nSystem RobDroneGo" as sys

actor -> sys: POST /buildings

activate sys
sys --> actor : building created / error in data
deactivate sys


@enduml
