@startuml
autonumber

participant "MDR" as mdr

[-> mdr: POST /clients

activate mdr
    alt user not created
        [<-- mdr : 422: Unprocessable Content
    else user created successfully
        [<-- mdr : 201: Created
    end
deactivate mdr

@enduml
