@startuml
autonumber

actor "Potential Client" as usr

participant "SPA" as ui



activate usr
    usr -> ui : wants to register as a client user
    activate ui
        ui --> usr : request data
    deactivate ui

    usr -> ui : provides data
    activate ui
        ui ->]  : POST /clients


            alt user not created
                ui <--]  : 422: error
                ui --> usr : informs error
            else success
                ui <--] : 201: user
                ui --> usr : shows created user
            end

    deactivate ui
deactivate usr

@enduml
