@startuml
autonumber

participant "??" as ui
mainframe MD
box "Back-End" #LightBlue

participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "building:\nBuilding" as b
participant "Mapper" as map
participant "dto:\nDTO" as dto
end box
box "Database"
database "Repository" as repo
end box

'activate ui
ui --> r: post(/buildings)

    activate r
        r -> ctrl : createBuilding(req,res)
            activate ctrl
                ctrl -> svc : createBuilding(bodyDTO)
                activate svc

                    svc --> b **: create()
                    activate b


                    alt building not created
                        svc --> ctrl : error
                        deactivate b
                        ctrl --> r : error (422)
                        r --> ui : 422: Unprocessable Content
                    else building created successfully
                    svc -> repo : save(building)
                    activate repo
                    deactivate repo

                    svc -> map : toDTO(building)
                    activate map
                        map --> dto **: create(building)
                        activate dto

                        map --> svc : dto
                        deactivate dto
                    deactivate map

                    svc --> ctrl : dto
                deactivate svc

                ctrl --> r : dto (201)
            deactivate ctrl




    r --> ui: 201: Created
deactivate r
    end
'deactivate ui

@enduml
