@startuml
autonumber

participant "??" as ui

participant "MD" as mdr
participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "Building" as b
participant "Mapper" as map
participant "DTO" as dto

participant "Repository" as repo


'activate ui
ui --> mdr: get(/elevators)
    activate mdr
    mdr -> r : get(/elevators)

    activate r
        r -> ctrl : buildingElevators

            activate ctrl
                ctrl -> svc : buildingElevators
                activate svc
                note right: all elevators in choosed building
                    svc -> repo : buildingElevators
                    activate repo
                    repo -> repo: queries DB


                    svc -> map : toDTO()
                    deactivate repo
                    activate map
                        map --> dto : create()
                        activate dto
                        deactivate dto
                        map --> svc : dto
                    deactivate map

                    svc --> ctrl : dto
                deactivate svc

                ctrl --> r : dto (200)
            deactivate ctrl

        r --> mdr : dto (200)
        deactivate r

    mdr --> ui: dto (200)
    deactivate mdr
'deactivate ui

@enduml
