@startuml
autonumber

actor "Campus Manager" as usr

participant "Campus UI" as ui

'TODO: call it just 'MD'?
participant "Campus MD" as md

activate usr
    usr -> ui : list floors from a building
    activate ui
        ui -> md : GET /buildings
        activate md
            note right : see us170 documentation
            md --> ui : buildings
        deactivate md
        ui --> usr : request data
    deactivate ui

    usr -> ui : provides data
    activate ui
        ui -> md : GET /buildings/{code}/floors
        activate md
            note right : see us210 documentation
            alt success
                md --> ui : floors
                ui --> usr : lists floors
            else error
                md --> ui : error
                ui --> usr : informs error
            end
        deactivate md
    deactivate ui
deactivate usr

@enduml
