@startuml
autonumber

actor "Client" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
usr -> sys : wants to register a new delivery task
activate sys
sys --> usr : requests pickup and delivery buildings
deactivate sys
usr -> sys : provides buildings

activate sys
    sys --> usr : requests pickup and delivery floors
deactivate sys

usr -> sys : provides floors
activate sys
sys --> usr : requests pickup and delivery rooms
deactivate sys

usr -> sys : provides rooms
activate sys
sys --> usr : requests task details
deactivate sys

usr -> sys : provides task details
activate sys
sys --> usr : previews newly created task
deactivate sys
deactivate usr

@enduml
