@startuml

skinparam component {
    FontSize 16
    BackgroundColor<<Apache>> LightCoral
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BorderColor black
    BackgroundColor DeepSkyBlue
    ArrowFontName Impact
    ArrowColor #FF6655
}

package system {
    package "Infrastructure" {
        package "Routes" {
            class RouteBuilding
        }

        package "Persistence" {
            interface IDBDriver
            class DBDriver
        }

        DBDriver -right-|> IDBDriver
    }

    package "Interface Adapters" {
        package "Controllers" {
            package "IControllers" {
                interface IControllerBuilding
            }

            package "ImplControllers" {
                class ControllerBuilding
            }
            ControllerBuilding -up-|> IControllerBuilding
        }

        package "Repositories" {
            class RepoBuilding

        }

        RepoBuilding .up.> DBDriver


        RouteBuilding ..> IControllerBuilding
    }

    package "Application Services" {
        package "App Services" {
            package "IAppServices" {
                interface IAppServiceBuilding
            }

            package "ImplAppServices" {
                class AppServiceBuilding
            }

            AppServiceBuilding --|> IAppServiceBuilding

            package "IRepositories" {
                interface IRepoBuilding

            }

            RepoBuilding --|> IRepoBuilding

        }

        ControllerBuilding ..> IAppServiceBuilding

        AppServiceBuilding .up.> IRepoBuilding
    }

    package "Entities/Core/Domain" {
        package "Aggregates" {


            package "Building" as a_building {
                entity Building <<root>> <<entity>>
            }
        }



        package "Value Objects" {
            package "Building" as vo_building {
                class BuildingCode
                class BuildingName
                class BuildingDescription
                class BuildingDimensions
            }
        }


        Building "1" --> "1" BuildingCode
        Building "1" --> "1" BuildingName
        Building "1" --> "1" BuildingDescription
        Building "1" --> "1" BuildingDimensions

        AppServiceBuilding ..> Building

    }

    package "DTO" {
        interface IBuildingDTO

    }
    AppServiceBuilding -up-> IBuildingDTO
    ControllerBuilding -up-> IBuildingDTO
}

@enduml

