@startuml
autonumber

participant "<<system>>\nSystem RobDroneGo" as sys

[-> sys : POST /buildings/{id}/elevators

activate sys
    alt building not found
        [<-- sys : 404: Not found
    else floor(s) not found
        [<-- sys : 404: Not found
    else elevator not created
        [<-- sys : 422: Unprocessable Content
    else elevator created successfully
        [<-- sys : 201: Created
    end
deactivate sys

@enduml
