@startuml
autonumber

actor "??" as actor
participant "<<system>>\nSystem RobDroneGo" as sys

activate actor
    actor -> sys: Inserts requested data(code,building,floors covered)

    activate sys
    sys --> actor : Message: elevator created / error in data inserted
    deactivate sys
deactivate actor


@enduml
