@startuml
autonumber

actor "Campus Manager" as usr

participant "Campus UI" as ui
participant "Campus MD" as md

activate usr
    usr -> ui : list building floors with passages
    activate ui
        ui -> md : GET /buildings
        activate md
            note right of md : see US 170
            md --> ui : buildings
        deactivate md

        ui --> usr : show buildings and request one
    deactivate ui

    usr -> ui : chooses building
    activate ui
        ui -> md : GET /buildings/{id}/floors/passages
        activate md
            note right of md : see US 220
            md --> ui : building floors with passages
        deactivate md

        ui --> usr : inform error/show floors
    deactivate ui
deactivate usr

@enduml
