@startuml
autonumber

actor "Campus Manager" as usr

participant "Campus UI" as ui
participant "Campus MD" as md

activate usr
    usr -> ui : wants to create elevator
    activate ui
        ui -> md : GET /buildings
        activate md

         alt building(s) not found
                md --> ui : 204: empty list
                ui --> usr :  informs building(s) not found
         else building(s) found
            note right of md : see US 170 documentation
            md --> ui : 200: buildings
            deactivate md

        ui --> usr : shows buildings and request one
    deactivate ui

    usr -> ui : chooses building
    activate ui
        ui -> md : GET /buildings/{id}/floors
        activate md

        alt floor(s) not found
                md --> ui : 204: empty list
                ui --> usr :  informs floor(s) not found
        else floor(s) found

            note right of md : see US 210 documentation
            md --> ui : 200: floors
        deactivate md

        ui --> usr : shows floors and request data
    deactivate ui

    usr -> ui: chooses floors and provides\n elevator data
    activate ui
        ui -> md : POST /buildings/{id}/elevators
        activate md

            alt elevator not created
                 md --> ui : 422: error
                 ui --> usr :  informs error
            else elevator created successfully


            note right of md : see US 270 documentation
            md --> ui : 201: elevator
        deactivate md
        ui --> usr : preview elevator
        end
    end
end
    deactivate ui
deactivate usr

@enduml
