@startuml
autonumber

participant "<<system>>\nSystem RobDroneGo" as sys

    [-> sys: POST /building/{id}/floors

    activate sys
    alt building not found
        [<--sys : 404 not found
    else floor already exists
        [<--sys : 422 Unprocessable Content
    else floor created successfully
        [<--sys : 201 created
    end
    deactivate sys


@enduml
