@startuml
autonumber

actor " " as actor
participant "<<system>>\nSystem RobDroneGo" as sys

activate actor
    actor -> sys: POST /floor

    activate sys
    alt building not found
        sys --> actor : 412: Precondition Failed
    else floor created successfully
        sys --> actor : 201: Created
    end
    deactivate sys
deactivate actor


@enduml
