@startuml
autonumber

participant "Fleet Manager" as ui

mainframe MD
box "Back-End" #LightBlue
participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "Mapper" as map
participant "dto:\nDTO" as dto
end box

box "Database"
database "Repository" as repo
end box

ui--> r: GET /robots
    activate r
note right : verify if user is a \nfleet manager
    alt unkown user
        r --> ui : 401: Unauthorized
    else user not authorized
        r --> ui : 403: Forbidden
    else user authorized
        r -> ctrl : getRobots(req,res)
        activate ctrl
            ctrl -> svc : getRobots()
            activate svc
                svc -> repo : findAll()
                activate repo
                deactivate repo

                alt robots not found
                    svc --> ctrl : error
                    ctrl --> r : error (412)
                    ui<--r : 412: Precondition Failed
                else robots found

                loop for each robot

                        svc -> map : toDTO(robot)


                    activate map
                        map --> dto** : create(robot)
                        activate dto
                            map --> svc : dto
                        deactivate dto
                    deactivate map
                end loop
                    svc --> ctrl : dto
                    ctrl --> r : response
                    ui<-- r : 200: "OK" Successful
                end
            deactivate svc
        deactivate ctrl
        end
    deactivate r

@enduml
