@startuml
autonumber

actor "Campus Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
    usr -> sys : update floor map
    activate sys
        sys --> usr : shows buildings and request one
    deactivate sys

    usr -> sys : chooses building
    activate sys
        sys --> usr: shows floors
    deactivate sys
        usr -> sys : chooses floor
    activate sys
        sys --> usr : request map
    deactivate sys
        usr -> sys : provides map
    activate sys
        sys --> usr : inform error/success
    deactivate sys
deactivate usr

@enduml
