@startuml
autonumber

actor "Fleet Manager" as actor
participant "<<system>>\nSystem RobDroneGo" as sys

activate actor
    actor -> sys: POST /robottypes

    activate sys
    alt unkown user
        sys --> actor : 401: Unauthorized
    else user not autorized
        sys --> actor : 403: Forbidden
    else user authorized
        alt robot type not created
            sys --> actor : 422: Unprocessable Content
        else robot type created successfully
            sys --> actor : 201: Created
        end
    end

    deactivate sys
deactivate actor


@enduml
