@startuml
autonumber

participant "<<system>>\nSystem RobDroneGo" as sys

[-> sys: PATCH /building/{id}/floors/{number}/map
activate sys

alt floor not found
    [<--sys  : 404 not found
else map not processed
    [<--sys : 422 Unprocessable Content
else floor map updated
    [<--sys  : 200 OK
end

deactivate sys

@enduml
