@startuml
autonumber

participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc
participant "Repository" as repo

participant "Mapper" as map
participant "dto:\nDTO" as dto


[-> r : GET /passages
activate r

    r -> ctrl : getPassages()
    activate ctrl

        ctrl -> svc : getPassagesBetweenBuildings(bCode1, bCode2)
        activate svc

            svc -> repo : findByCode(buildingCode1)
            activate repo
                repo ->] : find()
            deactivate repo

            svc -> repo : findByCode(buildingCode2)
            activate repo
                repo ->] : find()
            deactivate repo

            alt building not found
                svc --> ctrl : error
                ctrl --> r : error (404)
                [<-- r : 404: Not found
            else building found
                svc --> svc : sameBuilding(building)


                alt same building
                    svc --> ctrl : error
                    ctrl --> r : error (412)
                    [<-- r : 422: Unprocessable Content
                else different building
                    svc -> repo : passagesBetweenBuildings(building1, building2)
                    activate repo
                    deactivate repo

                    alt passages not found
                        svc --> ctrl : error
                        ctrl --> r : error (404)
                        [<-- r : 404: Not found
                    else passages found
                        loop for each passage
                             svc -> map : toDTO(passage)
                            activate map
                                map --> dto** : create(passage)
                                activate dto
                                    map --> svc : dto
                                deactivate dto
                            deactivate map
                        end loop

                        svc --> ctrl : dto
                        ctrl --> r : dto(200)
                        [<-- r : 200: Ok
                    end
                end
            end
        deactivate svc
    deactivate ctrl
deactivate r

@enduml
