@startuml
autonumber

participant "<<system>>\nMD" as mdr

[-> mdr: POST /passages
activate mdr
    alt floor not found
        [<-- mdr : 404 not found
    else same building
        [<-- mdr : 422 Unprocessable Content
    else passage already exists
        [<-- mdr : 422 Unprocessable Content
    else passage created successfully
        [<-- mdr : 201 Created
    end
deactivate mdr

@enduml

