@startuml
autonumber

actor "Campus Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
    usr -> sys : edit passage between two buildings
    activate sys
alt buildings not found
        sys --> usr : informs error
else buildings found
        sys --> usr : requests user to select two buildings
    deactivate sys

    usr -> sys : selects two buildings
    activate sys
alt passages not found 
        sys --> usr : informs error
else passages found
        sys --> usr : requests user to select passage to edit
    deactivate sys

    usr -> sys : selects passage
    activate sys
        sys --> usr : requests data to update passage
    deactivate sys

    usr -> sys : provides data
    activate sys
        sys --> usr : informs success
    deactivate sys
deactivate usr
end
end

@enduml
