@startuml
autonumber

actor "Campus Manager" as usr

participant "HTML + CSS + JS" as view
participant "Controller" as ctrl
participant "Service" as svc
participant "dto:\nBuildingDTO" as dto
participant "dto:\nFloorAndBuildingDTO" as dtofb
participant "dto:\nRoomDTO" as dtor
participant "dto:\nCreatedRoomDTO" as dtocr


participant "HTTP Driver" as http



activate usr
usr -> view : wants to create room
    activate view
        view -> ctrl : ngOnInit()
        activate ctrl
            ctrl -> svc : getBuildings()
            activate svc
                svc -> http : get({baseURL}/buildings)
                activate http
                    http ->] : GET /buildings
        alt building(s) not found

                note right : see us170 documentation
                 http <--] : 404: error
                http --> svc : observable
                svc --> ctrl : []
                ctrl --> ctrl : buildings = []
                note bottom : creates alert with the error message
                ctrl --> view : buildings
                view --> usr : does not list anything
        else building(s) found
                http <--] : 200: buildings

            http --> svc : observable
            deactivate http

            loop for each building
                svc --> dto** : create()
                activate dto
                    dto --> svc : dto
                deactivate dto
            end

            svc --> ctrl : dto[]
            deactivate svc

            ctrl --> ctrl : buildings = dto[]
            ctrl --> view : buildings
            deactivate ctrl

            view --> usr : shows buildings and \nrequest one
        deactivate view

        usr -> view : chooses building
        activate view
            view -> ctrl : listFloors()
            activate ctrl
                ctrl -> svc : listFloors()
                activate svc
                    svc -> http : get({baseURL}/buildings/{buildingCode}/floors)
                    activate http
                        http ->] : GET /buildings/{id}/floors

             alt floors(s) not found

                    note right : see us210 documentation
                    http <--] : 404: error
                    http --> svc : observable
                    svc --> ctrl : []
                    ctrl --> ctrl : floors = []
                    note bottom : creates alert with the error message
                    ctrl --> view : floors
                    view --> usr : does not list anything
             else floor(s) found
                http <--] : 200: floors

                    http --> svc : observable
                    deactivate http

                    loop for each floor
                        svc --> dtofb** : create()
                        activate dtofb
                            dtofb --> svc : dto
                        deactivate dtofb
                    end

                    svc --> ctrl : dto[]
                deactivate svc

                ctrl --> ctrl : floors = dto[]
                ctrl --> view : floors
            deactivate ctrl
            view --> usr : shows floors and \nrequest data
        deactivate view

        usr -> view : chooses floors and\nprovides room data
        activate view
            view -> ctrl : onSubmit()
            activate ctrl
                ctrl --> dtor** : create()
                activate dtor
                    dtor --> ctrl : dto
                deactivate dtor

                ctrl -> svc : createRoom(buildingCode, floorNumber, dto)
                activate svc

                    svc -> http : post({baseURL}/buildings/{buildingCode}/floors/{floorNumber}/rooms)
                    activate http
                        http ->] : POST /buildings/{buildingId}/floors/{floorNumber}/rooms

                note right : see us310 documentation
                alt room bad parameters
                    http <--] : 422: error
                    http --> svc : observable
                    svc --> ctrl : error
                    note bottom : creates alert with the error message
                    ctrl --> view : createdRoom
                    view --> usr : informs error

                else room already exists
                    http <--] : 422: error
                                        http --> svc : observable
                                        svc --> ctrl : error
                                        note bottom : creates alert with the error message
                                        ctrl --> view : createdRoom
                                        view --> usr : informs error
                else room created successfully

                    http <--] : 201: room
                    http --> svc : observable

                    svc --> dtocr** : create()
                    activate dtocr
                        dtocr --> svc : dto
                    deactivate dtocr

                    svc --> ctrl : dto

                    ctrl --> ctrl : createdRoom = dto
                    note bottom : creates alert with success message
                    ctrl --> view : createdRoom
                    view --> usr : previews created \nroom information


                    deactivate http
                    deactivate svc
                    deactivate ctrl
                    deactivate view

                    deactivate usr
                end
            end
            end
@enduml
