@startuml
autonumber

actor "Fleet Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
    usr -> sys : wants to create robot
    activate sys
    alt robot type(s) not found
        sys --> usr : informs error
    else robot type(s) found
        sys --> usr : requests robot type
    deactivate sys

    usr -> sys : provides robot type
    activate sys
        sys --> usr : requests data
    deactivate sys

    usr -> sys : provides data
    activate sys
    alt bad robot parameters
        sys --> usr : informs error
    else success
        sys --> usr : previews created robot
    deactivate sys
deactivate usr
end
end

@enduml
