@startuml

autonumber

actor "Client" as usr
participant "SPA" as ui
participant "MDR" as md

activate usr
usr -> ui : wants to edit client data
    activate ui
        ui -> md : GET /clients/{email}
        activate md
alt client not found
            md --> ui : 404: error
            ui --> usr : informs error
else client found
            md --> ui : 200 : client
        deactivate md
        ui --> usr : requests data
    deactivate ui

    usr -> ui : provides data
    activate ui
    ui -> md : PATCH /clients/{email}
        activate md
alt bad client parameters
            md --> ui : 422: error
            ui --> usr : informs error
else success
            md --> ui : 200: client
            ui --> usr : previews edited client data
        deactivate md
    deactivate ui
deactivate usr
end
end

@enduml
