@startuml
autonumber

participant "<<system>>\nSystem RobDroneGo" as sys

[-> sys: PATCH/PUT  ( /buildings/{id}/floors/{floor} )
activate sys
    alt  building not found
            [<-- sys : 404: Not Found
        else building found
            alt floor not found
                [<-- sys : 404: Not Found
            else floor found
                alt floor bad parameters
                    [<-- sys : 422: Unprocessable Content
                else floor correct parameters
                    [<-- sys : 200: OK
            end
        end
    end
deactivate sys

@enduml
