@startuml

skinparam component {
    FontSize 16
    BackgroundColor<<Apache>> LightCoral
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BorderColor black
    ArrowFontName Impact
    ArrowColor #FF6655
    ArrowFontColor #777777
}


component system {
    package "Frameworks and Drivers Layer" {
        [Routing]
        [Persistence]
    }

    package "Interface Adapters Layers" {
        [Controller]
        [Repository]
    }

    package "Application Business Rules" {
        [Application Service]
    }

    package "Enterprise Business Rules" {
        [Domain Model (DDD)]
    }

    portin " " as port1
    portout " " as port2

    [Routing] -- port1
    [Persistence] --( "Data Model API"
    [Persistence] -- "Persistence API"

    [Controller] -up- "Controller API"
    [Routing] -down-( "Controller API"

    [Repository] -up- "Data Model API"
    [Repository] -up-( "Persistence API"

    [Controller] -down-( "App Service API"
    [Controller] -down-( "DTO API"

    "DTO API" -left- [DTO]

    [Application Service] -up- "App Service API"
    [Application Service] -up-( "DTO API"
    [Repository] -- "Repo API"
    [Application Service] -up-( "Repo API"

    [Repository] -down-( "Model API"
    [Application Service] --( "Model API"
    [Domain Model (DDD)] -up- "Model API"

}
"FS API" -- port2
"MDR API" -- port1

@enduml

