@startuml
autonumber

actor "Campus Manager" as usr

participant "HTML + CSS + JS" as view
participant "Controller" as ctrl
participant "PassageDTO" as passageDTO
participant "BuildingService" as buildingSvc
participant "FloorService" as floorSvc
participant "PassageService" as passageSvc
participant "FloorDTO" as floorDTO
participant "BuildingDTO" as dto

participant "HTTP Driver" as http

activate usr
usr -> view : wants to list buildings
    activate view
        view -> ctrl : ngOnInit()
        activate ctrl
            ctrl -> buildingSvc : getBuildings()
            activate buildingSvc
                buildingSvc -> http : get({baseURL}/buildings)
                activate http
                    http ->]: GET /buildings
                note right : see us170 documentation
                ]--> http : 200
                http --> buildingSvc : observable
                deactivate http
                loop for each building
                    buildingSvc --> dto** : create()
                    activate dto
                        dto --> buildingSvc : dto
                    deactivate dto
                end
                buildingSvc --> ctrl : buildings
        alt buildings empty
                ctrl --> view : error message
                view --> usr : shows error message
        else building(s) found
            ctrl --> view : buildings
            deactivate ctrl
            view --> usr : shows buildings
            deactivate
        deactivate view
        usr -> view : chooses building
        note right
            the following is the process when
            each of the building is chosen
        end note
        activate view
            view -> ctrl : listFloors(building)
            activate ctrl
                ctrl --> dto** : create()
                activate dto
                    dto --> ctrl : dto
                deactivate dto
                ctrl -> floorSvc : listFloors(building)
                activate floorSvc
                    floorSvc -> http : get({baseURL}/buildings/{buildingCode}/floors)
                    activate http
                        http ->] : GET /buildings/{id}/floors
                ]--> http : 200
                note right : see us210 documentation
                    http --> floorSvc : observable
                    deactivate http
                    loop for each floor
                        floorSvc --> floorDTO** : create()
                        activate floorDTO
                            floorDTO --> floorSvc : floorDTO
                        deactivate floorDTO
                    end
                    floorSvc --> ctrl : floors
                deactivate floorSvc
                    alt floors is empty
                        ctrl --> view : floors not found
                        view --> usr : shows error
                    else floors found

                ctrl --> view : floors
            deactivate ctrl
            view --> usr : requests floor
        deactivate view

        usr -> view : submit after choosing floors
        activate view
            view -> ctrl : formData
            activate ctrl
                ctrl-> passageDTO**: create()
                activate passageDTO
                    ctrl-> passageDTO: passageDTO
                deactivate passageDTO
                ctrl -> passageSvc : createPassage(passage)
                activate passageSvc
                    passageSvc -> http : post({baseURL}/passages)
                    activate http
                        http ->] : POST /passages
                            ]--> http : status code
                note right : see us160 documentation
                    http --> passageSvc : observable
                    deactivate http
                    alt status==200
                    passageSvc --> ctrl : map

                ctrl --> view : map
                view --> usr : shows success message
                else
                    passageSvc --> ctrl : error message
                    deactivate passageSvc
                ctrl --> view : error message
                deactivate ctrl
            view --> usr : shows error message
            deactivate view
        deactivate usr
    end
    end
    end
@enduml
