@startuml
autonumber

actor " " as actor
box "RobDroneGo"
participant "MD" as mdr

activate actor
    actor -> mdr: PATCH/PUT  ( /buildings/{id}/floors/{floor} )
        activate mdr

        alt  floor not found
        mdr --> actor : 412: Precondition Failed
            else floor bad params
            mdr --> actor : 422: Unprocessable Content
        else floor edited successfully
            mdr --> actor : 200: "OK" Successful
        end

    deactivate mdr
deactivate actor


@enduml

