@startuml
autonumber

participant "MD" as mdr

[-> mdr : POST /buildings/{id}/elevators

activate mdr
    alt building not found
        [<-- mdr : 412: Precondition Failed
    else floor(s) not found
        [<-- mdr : 412: Precondition Failed
    else elevator not created
        [<-- mdr : 422: Unprocessable Content
    else elevator created successfully
        [<-- mdr : 201: Created
    end
deactivate mdr

@enduml
