@startuml
autonumber

actor "Campus Manager" as usr

participant "Campus UI" as ui

'TODO: call it just 'MD'?
participant "Campus MD" as md

activate usr
    usr -> ui : create building
    activate ui
        ui --> usr : request data
    deactivate ui

    usr -> ui : provides data
    activate ui
        ui -> md : POST /buildings
        activate md
            note right of md : see US 150 documentation

            alt building not created
                md --> ui : 422: error
                ui --> usr : informs error
            else success
                md --> ui : 201: elevator
                ui --> usr : previews created building

        deactivate md

        end
    deactivate ui
deactivate usr

@enduml
