@startuml
autonumber


participant "<<system>>\nSystem RobDroneGo" as sys

 [-> sys: GET /buildings/{id}/floors

activate sys
alt building not found
    [<--sys : response code: 404
else building found
    alt floors not found
        [<--sys : response code: 404
    else floors found
        [<--sys : response code: 200
    end
end
deactivate sys


@enduml
