@startuml
autonumber

participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "floor:\nFloor" as floor
participant "Mapper" as map
participant "dto:\nDTO" as dto

participant "Repository" as repo
database "Database" as db

[-> r: post(/building/{id}/floors)
activate r
    r -> ctrl : createFloor()
    activate ctrl
        ctrl -> svc : createFloor(dto)
        activate svc
            svc -> repo : findByCode(buildingCode)
            activate repo
                repo -> db : find()
                activate db
                    db --> repo : building
                deactivate db
                repo --> svc : building
            deactivate repo

            alt building not found
                svc --> ctrl : error
                ctrl --> r : error (404)
                [<--r : 404: Not Found
            else building found
                svc ->repo : findByCodeNumber(buildingCode,floorNumber)
                activate repo
                    repo -> db : find()
                    activate db
                        db --> repo : floor
                    deactivate db
                    repo --> svc : floor
                deactivate repo
            alt floor already exists
                svc --> ctrl : error
                ctrl --> r : error (422)
                [<--r : 422: Unprocessable Content
            else floor doesn't exist
                svc --> floor** : create()
                svc -> repo : save(floor)
                activate repo
                    repo -> db : save()
                    activate db
                    deactivate db
                deactivate repo

                svc -> map : toDTO(floor)

                activate map
                    map --> dto** : create(floor)
                    activate dto
                        map --> svc : dto
                    deactivate dto
                deactivate map

                svc --> ctrl : dto
                ctrl --> r : dto (201)
                [<--r : 201: Created
            end
            end
        deactivate svc
    deactivate ctrl
deactivate r

@enduml
