@startuml
autonumber

actor "Client" as usr

participant "SPA" as ui
participant "MDR" as mdr
participant "MDT" as mdt

activate usr
usr -> ui : wants to register a new delivery task
    activate ui
        ui -> mdr : GET /buildings
        activate mdr
            note right : see us170 documentation
            mdr --> ui : 200: buildings
        deactivate mdr

        ui --> usr : requests pickup and delivery buildings
        deactivate ui

        usr -> ui : provides buildings
        activate ui
        ui -> mdr : GET /buildings/{id}/floors
            activate mdr
            note right : see us210 documentation
                mdr --> ui : 200: floors
            deactivate mdr

            ui --> usr : requests pickup and delivery floors
        deactivate ui

        usr -> ui : provides floors
        activate ui
            ui -> mdr : GET /buildings/{id}/floors/$floorNumber}/rooms
            activate mdr
                note right : see us320 documentation
                mdr --> ui : 200: rooms
            deactivate mdr
            ui --> usr : requests pickup and delivery rooms
        deactivate ui

        usr -> ui : provides rooms
        activate ui
            ui --> usr : requests task details
        deactivate ui

        usr -> ui : provides task details
    activate ui
        ui -> mdr : POST /task/delivery
        activate mdr
            mdr -> mdt : POST /jobs
            activate mdt
                    mdt --> mdr : 201: task
                    deactivate mdt
                    mdr --> ui : 201: task
                    deactivate mdr
                    ui --> usr : previews newly created task
    deactivate ui
deactivate usr
@enduml
