@startuml
autonumber

actor "Fleet Manager" as usr

participant "Fleet UI" as ui

'TODO: call it just 'MD'?
participant "Fleet MD" as md

activate usr
    usr -> ui : list all fleet robots
    activate ui

        ui -> md: GET /robots
    activate md
        note right of md : see US 380
        md --> ui: list of robots in the fleet
    deactivate md


        ui --> usr : inform error / shows robots
    deactivate ui
deactivate usr

@enduml
