@startuml
autonumber

participant "<<system>>\nSystem RobDroneGo" as sys

 [-> sys: GET /buildings/?minFloors={min}&maxFloors={max}

activate sys
    alt building(s) not found
        [<--sys : response code: 422
    else building(s) found
        [<--sys : response code: 200
    end
deactivate sys


@enduml
