@startuml
autonumber

actor "Campus Manager" as usr

participant "HTML + CSS + JS" as view
participant "Controller" as ctrl
participant "BuildingService" as svc
participant "BuildingDTO" as dto

participant "HTTP Driver" as http

activate usr
usr -> view : wants to list buildings
    activate view
        view -> ctrl : ngOnInit()
        activate ctrl
            ctrl -> svc : getBuildings()
            activate svc
                svc -> http : get({baseURL}/buildings)
                activate http
                    http ->] : GET /buildings
                note right : see us170 documentation
                ]-> http : 200
                http --> svc : observable
                deactivate http
                loop for each building
                svc --> dto** : create()
                    activate dto
                        dto --> svc : dto
                    deactivate dto
                end
                svc --> ctrl : buildings
        alt buildings empty
                deactivate svc
                ctrl --> view : buildings
                view --> usr : informs there are no buildings
        else building(s) found
            ctrl --> view : buildings
            deactivate ctrl
            view --> usr : shows buildings
            deactivate view
        end
@enduml
