@startuml

skinparam component {
    FontSize 16
    BackgroundColor<<Apache>> LightCoral
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BorderColor black
    BackgroundColor DeepSkyBlue
    ArrowFontName Impact
    ArrowColor #FF6655
}

package system {
    package "Infrastructure" {
        package "Routes" {
            class RouteBuilding
        }

        package "Persistence" {
            interface IDBDriver
            class DBDriver
        }

        DBDriver -right-|> IDBDriver
    }

    package "Interface Adapters" {
        package "Controllers" {
            package "IControllers" {
                interface IControllerRoom
            }

            package "ImplControllers" {
                class ControllerRoom
            }
            ControllerRoom -up-|> IControllerRoom
        }

        package "Repositories" {
            class RepoBuilding
            class RepoFloor
            class RepoRoom

        }

        RepoBuilding .up.> DBDriver
        RepoFloor .up.> DBDriver
        RepoRoom .up.> DBDriver


        RouteBuilding ..> IControllerRoom
    }

    package "Application Services" {
        package "App Services" {
            package "IAppServices" {
                interface IAppServiceRoom
            }

            package "ImplAppServices" {
                class AppServiceRoom
            }

            AppServiceRoom --|> IAppServiceRoom

            package "IRepositories" {
                interface IRepoBuilding
                interface IRepoFloor
                interface IRepoRoom

            }

            RepoBuilding --|> IRepoBuilding
            RepoFloor --|> IRepoFloor
            RepoRoom --|> IRepoRoom

        }

        ControllerRoom ..> IAppServiceRoom

        AppServiceRoom .up.> IRepoBuilding
        AppServiceRoom .up.> IRepoFloor
        AppServiceRoom .up.> IRepoRoom

    }

    package "Entities/Core/Domain" {
        package "Aggregates" {

            package "Building" as a_building {
                        entity Building <<root>> <<entity>>
                    }

            package "Floor" as a_floor {
                        entity Floor <<root>> <<entity>>
                    }


            package "Room" as a_room {
                entity Room <<root>> <<entity>>
            }
        }



        package "Value Objects" {
            package "Room" as vo_room {
                class RoomName
                class RoomDescription
                class RoomCategory
                class RoomDimensions
                class Coordinates
            }
        }


        Room "1" --> "1" RoomName
        Room "1" --> "1" RoomDescription
        Room "1" --> "1" RoomCategory
        Room "1" --> "1" RoomDimensions
        Room "1" --> "1" Coordinates

        Room -left-> "1" Building
        Room -up-> "1" Floor


        AppServiceRoom ..> Room

        'package "Services" {
        '}
    }
    package "DTO" {
                  interface IRoomDTO
            }
            AppServiceRoom --> IRoomDTO
            ControllerRoom -up-> IRoomDTO
}

@enduml

