@startuml
autonumber

participant "<<system>>\nSystem RobDroneGo" as sys

[-> sys: POST /robots

activate sys
    alt unkown user
        [<-- sys : 401: Unauthorized
    else user not autorized
        [<-- sys : 403: Forbidden
    else robot not created
        [<-- sys : 422: Unprocessable Content
    else robot created successfully
        [<-- sys : 201: Created
    end
deactivate sys

@enduml
