@startuml
autonumber

participant "MD" as mdr



    [-> mdr: POST /robottypes

    activate mdr
    alt unkown user
        [<-- mdr  : 401: Unauthorized
    else user not autorized
        [<-- mdr  : 403: Forbidden
    else user authorized
    alt robttype already exists
        [<-- mdr: 412: Precondition failed
    else robot type not found
        alt robot type not created
            [<-- mdr  : 422: Unprocessable Content
        else robot type created successfully
            [<-- mdr  : 201: Created
            end
        end
    end
    deactivate mdr



@enduml
