@startuml
autonumber


participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc


participant "Mapper" as map
participant "dto:\nDTO" as dto

participant "Repository" as repo
database "Database" as db

[-> r: PATCH (buildings/{id}/floors/{floor})
activate r
    r -> ctrl : patchFloor(req,res,...)
        activate ctrl
            ctrl -> svc : patchFloor(dto)
            activate svc
                svc -> repo : findByCode(buildingCode)
                activate repo
                    repo -> db : find()
                    activate db
                        db --> repo : building
                    deactivate db
                    repo --> svc : building
                deactivate repo

                alt building not found
                    svc --> ctrl : error
                    ctrl --> r : response 404
                    [<--r : 404: Not Found
                else building found
                    svc -> repo : findByCodeNumber(buildingCode, floorNumber)
                    activate repo
                        repo -> db : find()
                        activate db
                            db --> repo : floor
                        deactivate db
                        repo --> svc : floor
                    deactivate repo

                    alt floor not found
                        svc --> ctrl : error
                        ctrl --> r : response 404
                        [<--r : 404: Not Found
                    else floor found
                        note right of svc
                            edit floor specifications
                            based on new ones
                        end note

                        alt floor bad parameters
                            svc --> ctrl : error
                            ctrl --> r : response 422
                            [<--r : 422: Unprocessable Content
                        else floor correct parameters
                            svc -> repo : save(floor)
                            activate repo
                                repo -> db : save()
                                activate db
                                deactivate db
                            deactivate repo

                            svc -> map : toDTO(floor)
                            activate map
                                map --> dto **: create(floor)
                                activate dto
                                    map --> svc : dto
                                deactivate dto
                            deactivate map
                            svc --> ctrl : dto
                        deactivate svc
                    ctrl --> r : response 200
                deactivate ctrl
                [<--r: 200: OK
            end
        end
    end
deactivate r

@enduml
