@startuml
autonumber

actor "Task Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
    usr -> sys :  Wants to list paths between two \nbuildings following a specific criteria
    activate sys

    deactivate sys
deactivate usr

@enduml
