@startuml
autonumber

actor "Task Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr
    usr -> sys : Wants to list paths between two \nbuildings following a specific criteria
    activate sys

            alt building(s) not found
                sys --> usr: informs building(s) not found
            else building(s) found
            sys --> usr : shows building and request two
        deactivate sys

        usr -> sys : chooses building
        activate sys
                alt floor(s) not found
                    sys --> usr: informs floor(s) not found
                else floor(s) found
                sys --> usr : shows floors and request two
        deactivate sys

        usr -> sys: chooses floors
        activate sys

                alt room not found
                    sys --> usr: informs room(s) not found
                else room(s) found
                    sys --> usr : shows rooms and request two
        deactivate sys

                usr -> sys: chooses rooms
                activate sys
                    sys --> usr: list paths

                deactivate sys

                    end
                end
            end
        deactivate sys
    deactivate usr

@enduml
