@startuml

skinparam component {
    FontSize 16
    BackgroundColor<<Apache>> LightCoral
    BorderColor<<Apache>> #FF6655
    FontName Courier
    BorderColor black
    BackgroundColor DeepSkyBlue
    ArrowFontName Impact
    ArrowColor #FF6655
    ArrowFontColor #777777
}

package "<<system>>\nRobDroneGo" {
    [Master Data]
}

api -left- [Master Data]

@enduml
