@startuml
autonumber

participant "??" as ui
participant "MD" as mdr


activate ui
    ui -> mdr: POST /buildings
    activate mdr
        mdr --> ui: building created/error
    deactivate mdr
deactivate ui

@enduml
