@startuml
autonumber

actor " " as actor
box "RobDroneGo"
participant "MD" as mdr

activate actor

    actor -> mdr: POST /building

    activate mdr
    alt building not created
        mdr --> actor : 422: Unprocessable Content
    else building created successfully
        mdr --> actor : 201: Created
    end
    deactivate mdr

deactivate actor

@enduml
