@startuml
autonumber

participant "Route" as r
participant "Controller" as ctrl
participant "Service" as svc

participant "passage:\nPassage" as passage
participant "Mapper" as map
participant "dto:\nDTO" as dto
participant "Repository" as repo

' TODO: @uz0maki review?

[--> r : POST /passages
activate r
    r ---> ctrl : createPassage()
    activate ctrl

        ctrl -> svc : createPassage(dto)
        activate svc

            svc -> repo : findByCode(buildingCode1)

            activate repo
                repo ->] : find()
            deactivate repo

            svc -> repo : findByCode(buildingCode2)
            activate repo
                repo ->] : find()
            deactivate repo

            alt building not found
                svc --> ctrl : error
                ctrl --> r : error (412)
                [<-- r : 412: Precondition Failed
            else building found
                svc --> svc : sameBuilding(buildingCode1,buildingCode2))
            alt same building
                svc --> ctrl : error
                ctrl --> r : error (412)
                [<--r : 412: Precondition Failed
            else building found
            svc -> repo : findByCode(floorNumber1)
            activate repo
                repo ->] : find()
            deactivate repo
            svc -> repo : findByCode(floorNumber2)
            alt floor not found
            svc --> ctrl : error
                ctrl --> r : error (412)
                [<--r : 412: Precondition Failed
            else
            activate repo
                repo ->] : find()
            deactivate repo
                    svc --> passage** : create(floor1,floor2)

                svc -> repo : save(passage)
            alt passage not created
                svc --> ctrl : error
                ctrl --> r : error (422)
                [<--r: 422: Unprocessable Content

            else passage created successfully

                activate repo
                    svc -> map : toDTO(passage)
                deactivate repo

                activate map
                    map --> dto** : create(passage)
                    activate dto
                        map --> svc : dto
                    deactivate dto
                deactivate map

                svc --> ctrl : dto
                deactivate svc
                ctrl --> r : dto (201)
                deactivate ctrl
                [<--r : 201: Created
            end
            end
            end
            end
deactivate r

@enduml
