@startuml
autonumber

actor "Administrator" as usr

participant "SPA" as ui



activate usr
    usr -> ui : wants to create a backoffice user
    activate ui
        ui --> usr : request data
    deactivate ui

    usr -> ui : provides data
    activate ui
        ui ->]  : POST /users-backoffice


            alt user not created
                ui <--]  : 422: error
                ui --> usr : informs error
            else success
                ui <--] : 201: user
                ui --> usr : shows created user
            end

    deactivate ui
deactivate usr

@enduml
