@startuml
autonumber

actor "Campus Manager" as usr

participant "HTML + CSS + JS" as view
participant "Controller" as ctrl
participant "Service" as svc
participant "dto:\nDTO" as dto

participant "HTTP Driver" as http

participant "MD" as md

activate usr
usr -> view : wants to create elevator
    activate view
        view -> ctrl : ngOnInit()
        activate ctrl
            ctrl -> svc : getBuildings()
            activate svc
                svc -> http : get({baseURL}/buildings)
                activate http
                    http -> md : GET /buildings
        alt building(s) not found
            activate md
                note right : see us170 documentation
                md --> http : 200: empty list
                http --> svc : observable
                svc --> ctrl : []
                ctrl --> ctrl : buildings = []
                ctrl --> view : buildings
                view --> usr : does not list anything
        else building(s) found
                md --> http : 200: buildings
            deactivate md
            http --> svc : observable
            deactivate http

            loop for each building
                svc --> dto** : create()
                activate dto
                    dto --> svc : dto
                deactivate dto
            end

            svc --> ctrl : dto[]
            deactivate svc

            ctrl --> ctrl : buildings = dto[]
            ctrl --> view : buildings
            deactivate ctrl

            view --> usr : shows buildings and \nrequest one
        deactivate view

        usr -> view : chooses building
        activate view
            view -> ctrl : listFloors()
            activate ctrl
                ctrl -> svc : listFloors()
                activate svc
                    svc -> http : get({baseURL}/buildings/{buildingCode}/floors)
                    activate http
                        http -> md : GET /buildings/{id}/floors
            activate md
             alt floors(s) not found
                activate md
                    note right : see us210 documentation
                    md --> http : 200: empty list
                    http --> svc : observable
                    svc --> ctrl : []
                    ctrl --> ctrl : floors = []
                    ctrl --> view : floors
                    view --> usr : does not list anything
             else floor(s) found
                md --> http : 200: floors
                deactivate md
                    http --> svc : observable
                    deactivate http

                    loop for each floor
                        svc --> dto** : create()
                        activate dto
                            dto --> svc : dto
                        deactivate dto
                    end

                    svc --> ctrl : dto[]
                deactivate svc

                ctrl --> ctrl : floors = dto[]
                ctrl --> view : floors
            deactivate ctrl
            view --> usr : shows floors and \nrequest data
        deactivate view

        usr -> view : chooses floors and\nprovides elevator data
        activate view
            view -> ctrl : onSubmit()
            activate ctrl
                ctrl --> dto** : create()
                activate dto
                    dto --> ctrl : dto
                deactivate dto

                ctrl -> svc : createElevator(buildingId,dto)
                activate svc

                    svc -> http : post({baseURL}/buildings/{buildingId}/elevators)
                    activate http
                        http -> md : POST /buildings/{id}/elevators
            activate md
                note right : see us270 documentation
                alt elevator not created
                    md --> http : 422: error
                    http --> svc : null
                    svc --> ctrl : null
                    ctrl --> ctrl : createdElevator = null
                    ctrl --> view : createdElevator
                    view --> usr : informs error

                else elevator created successfully

                    md --> http : 201: elevator
                    http --> svc : observable

                    svc --> dto** : create()
                    activate dto
                        dto --> svc : dto
                    deactivate dto

                    svc --> ctrl : dto

                    ctrl --> ctrl : createdElevator = dto
                    ctrl --> view : createdElevator
                    view --> usr : previews created \nelevator information

                    deactivate md
                    deactivate http
                    deactivate svc
                    deactivate ctrl
                    deactivate view

                    deactivate usr
                end
            end
            end
@enduml
