@startuml
autonumber


participant "<<system>>\nSystem RobDroneGo" as sys


    [-> sys: POST (/buildings/{buildingId}/floors/{floorNumber}/rooms)
    activate sys

    alt floor not found
        [<-- sys : 404: Not Found
    else floor found
    alt room not created
        [<-- sys : 422: Unprocessable Content
    else room created successfully
        [<-- sys : 201: Created
        end
    end

    deactivate sys

@enduml
