@startuml
autonumber

actor "Fleet Manager" as usr

participant "<<system>>\n System RobDroneGo" as sys

activate usr

    usr -> sys : wants to inhibit robot
    activate sys

    alt robotList empty
        sys --> usr: informs error
    else robot(s) found

        sys --> usr : show available robots
    deactivate sys

    usr -> sys : chooses robot
    activate sys

    alt inhibit error
        sys --> usr: informs error
    else success


        sys --> usr : show updated list of robots
    deactivate sys
deactivate usr
end
end
@enduml
