@startuml
autonumber

participant "<<system>>\n RobDroneGo" as sys

[-> sys: POST /clients

activate sys
    alt user not created
        [<-- sys : 422: Unprocessable Content
    else user created successfully
        [<-- sys : 201: Created
    end
deactivate sys

@enduml
