name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: MDR Lint and Test
        run: |
          cd mdr
          npm install
          npm run lint:fix
          npm test

      - name: SPA Test
        uses: cypress-io/github-action@v6
        with:
          build: |
            cd spa
            npm run build

          start: |
            cd spa
            npm start

  mdr_build:
    name: MDR Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: MDR Build
        run: |
          cd mdr
          npm install
          npm run build

  spa_build:
    name: SPA Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SPA Build
        run: |
          cd spa
          npm install
          npm run build
