name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: MDR Lint and Test
        run: |
          cd mdr
          npm install
          npm run lint:fix
          npm test

      - name: SPA Test
        run: |
          cd spa
          npm install
          npm run start & npx cypress run
          npx cypress run --component

  mdr_build:
    name: MDR Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: MDR Build
        run: |
          cd mdr
          npm install
          npm run build

  spa_build:
    name: SPA Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SPA Build
        run: |
          cd spa
          npm install
          npm run build
          
  mdt_build:
    name: MDT build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: MDT Build
        run: |
          cd mdt
          dotnet restore
          dotnet build
          
  mdt_test:
    name: MDT Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Restore and Test .NET Project
        run: |
          cd mdt.Tests
          dotnet restore
          dotnet test
