@startuml
autonumber

participant "MD" as mdr

[-> mdr: POST /robots

activate mdr
    alt unkown user
        [<-- mdr : 401: Unauthorized
    else user not autorized
        [<-- mdr : 403: Forbidden
    else robot not created
        [<-- mdr : 422: Unprocessable Content
    else robot created successfully
        [<-- mdr : 201: Created
    end
deactivate mdr

@enduml
